rootPageId: 1
base: /
baseVariants:
  -
    base: 'https://kist-escherich-com-v12.ddev.site/'
    condition: 'applicationContext == "Development"'
  -
    base: 'https://ps14.de/'
    condition: 'applicationContext == "Production"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=6'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    languageId: 1
    fallbackType: strict
    base: /en/
    typo3Language: default
    locale: en-GB.UTF-8
    navigationTitle: English
    hreflang: en
    direction: ''
    flag: gb
routes:
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /vendor/\r\nDisallow: /typo3_src/\r\nSitemap: https://ps14.de/sitemap.xml"
websiteTitle: Ps14
